specVersion: 0.0.1
description: Substrate slots auction data collector
repository: git@github.com:subvis-io/subquery-spectator.git
schema: ./schema.graphql
network:
  endpoint: wss://regnet2-relay-rpc.parallel.fi

dataSources:

  - name: KusamaRuntime
    kind: substrate/Runtime
    filter:
      specName: kusama
    startBlock: 0
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler

          #   filter:
          #     module: balances
          #     method: Deposit
          # - handler: handleCall
          #   kind: substrate/CallHandler

  - name: PolkadotRuntime
    kind: substrate/Runtime
    filter:
      specName: polkadot
    startBlock: 0
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
